name: Github actions

on:
  push:
    branches:
      - "**"
  pull_request:
    types:
      - opened

jobs:
  validation-typescript:
    name: Validation typescript
    uses: alexis-gss/github-workflows/.github/workflows/validation-typescript.yml@master
  deployment:
    name: Deployment production
    needs: ['validation-typescript']
    uses: alexis-gss/github-workflows/.github/workflows/deployment.yml@master
    secrets: inherit
    if: github.ref == 'refs/heads/master'